version: "3" # optional since v1.27.0
services:
  app:
    image: putra-t-api:latest
    ports:
      - "3000:3000"
    environment:
      - MYSQL_URL=mysql://root:3G2FAdgE2344a6eDCBHH-dGbdB3hFgBb@monorail.proxy.rlwy.net:51601/railway